name: Build iPhone App
on: [push, workflow_dispatch]
jobs:
  build:
      runs-on: macos-latesteps:
                - uses: actions/checkout@v4.
                - name: Build
                  run: |
                                        mkdir build
                                                  cd build
                                                            cmake .. -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64
                                                                      make -j4
                                                                            - name: Upload
                                                                                    uses: actions/upload-artifact@v4
                                                                                            with:
                                                                                                      name: Winlator-iOS
                                                                                                                path: build/box64
